files:
  - source: /src/main/resources/assets/seedcrackerx/lang/en_us
    translation: /src/main/resources/assets/seedcrackerx/lang/%locale_with_underscore%.json
  - source: README
    ignore:
      - READMEzh
      - READMEru
    translation: README%two_letters_code%.md
