pull_request_title: 'i18n: update crowdin translation'
commit_message: 'i18n: update translations for `%language%`'
files:
  - source: /src/main/resources/assets/seedcrackerx/lang/en_us
    translation: /src/main/resources/assets/seedcrackerx/lang/%locale_with_underscore%.json
  - source: README.md
    ignore:
      - READMEzh
      - READMEru
    translation: /Language/README%two_letters_code%.md
